services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ticket-booking-db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "-proot" ]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  kafka:
    image: obsidiandynamics/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge

    command: start-dev 
            --import-realm
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/inventory_db
    depends_on:
       mysql:
          condition: service_healthy

  booking-service:
    build: ./booking-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/booking_db
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - INVENTORY_SERVICE_URL=http://inventory-service:8081/api/inventory
    depends_on:
      - mysql
      - kafka
      - inventory-service

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIL_USERNAME=your-sandbox-smtp-username
      - SPRING_MAIL_PASSWORD=your-sandbox-smtp-password
    depends_on:
      - kafka

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/ticket-booking-realm
      - BOOKING_SERVICE_URI=http://booking-service:8082
      - INVENTORY_SERVICE_URI=http://inventory-service:8081
    depends_on:
      - redis
      - keycloak
      - booking-service
      - inventory-service
volumes:
  db-data:
